name: Inspector
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  release:
    types:
      - created

jobs:
  test_no_changes:
    runs-on: ubuntu-latest
    name: Test (no formatting changes)
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run IntelliJ Inspections
        uses: jacopocarlini/intellij-format-action@main
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INSPECTIONS_FILE: ./.idea/inspectionProfiles/Project_Default.xml
          IGNORE_FILE_PATTERNS: |
            []
