name: On Pull
on:
  workflow_dispatch:
  issue_comment:
    types: [ created, edited ]

jobs:
  test_with_auto_fix:
    runs-on: ubuntu-latest
    name: Test (with auto fix)
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run action
        id: test-action
        uses: findologic/intellij-format-action@main
        with:
          include-glob: '*.kt'
          path: .
          fail-on-changes: false

      - name: Commit files
        run: |
          git config --local user.email "test@test.com"
          git config --local user.name "Test"
          git commit -a -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
